### ISSUE TITLE
Sending without pageview

### ISSUE THREAD

**Issue by dottodot** [insidewarehouse/gampee#3]
Is there any other way of sending the data without having to use `pageview`?

**Comment by dominykas** [comment]
Yes, send it with an `event` :) It can probably also be sent with `transaction`, but I haven't tested that.

**Comment by dottodot** [comment]
OK I did try event and it didn't work

```
ga.event(ecommerceParams).send();
```

I'm guessing so have to send some event params i.e

```
ga.event(_.merge({ec: "Ecommerce Advanced", ea: "List"}, ecommerceParams)).send();
```

but ideally i don't want to record an event as well.

**Comment by djabif** [comment]
Hi @dottodot how did you resolve this? 
I'm facing the same issue... 
Thanks!

**Comment by dottodot** [comment]
@djabif I've stopped using this so I can't remember I'm afraid.

**Comment by djabif** [comment]
@dottodot thanks for your answer. Did you go directly with https://github.com/peaksandpies/universal-analytics?

**Comment by dottodot** [comment]
No I just use the methods as detailed in the Google Analytics docs so no need for any plugins.
